## EDA of the data with ontology filter

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('usda_final.csv')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 124125 entries, 0 to 124124
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   item_name     124125 non-null  str
 1   carbs_100g    124125 non-null  float64
 2   kcal_100g     124125 non-null  float64
 3   fat_100g      124125 non-null  float64
 4   protein_100g  124125 non-null  float64
 5   source        124125 non-null  str
 6   cat_l1        124125 non-null  str
 7   cat_l2        124125 non-null  str
 8   cat_l3        124125 non-null  str
dtypes: float64(4), str(5)
memory usage: 8.5 MB

In [13]:
df_cats = df[['item_name', 'cat_l1', 'cat_l2', 'cat_l3']]

In [14]:
for i in range(1, 4):
    print(f"Unique values in cat_l{i}: {df_cats[f'cat_l{i}'].nunique()}")

Unique values in cat_l1: 18
Unique values in cat_l2: 75
Unique values in cat_l3: 228

In [15]:
# check how many of the unique cat_l3 values are in cat_l2
cat_l2_values = set(df_cats['cat_l2'].unique())
cat_l3_values = set(df_cats['cat_l3'].unique())
cat_l3_in_l2 = cat_l3_values.intersection(cat_l2_values)
print(f"Number of unique cat_l3 values: {len(cat_l3_values)}")
print(f"Number of unique cat_l3 values that are also in cat_l2: {len(cat_l3_in_l2)}")

Number of unique cat_l3 values: 228
Number of unique cat_l3 values that are also in cat_l2: 25

In [16]:
print(cat_l3_in_l2)

{'milk', 'frozen vegetables', 'water', 'powdered drinks', 'canned vegetables', 'bread', 'cereal', 'rice', 'vegetable & cooking oils', 'cookies & biscuits', 'chewing gum & mints', 'dried fruits', 'salad dressing & mayonnaise', 'frozen fish & seafood', 'chocolate', 'frozen dinners & entrees', 'cheese', 'pizza', 'yogurt', 'ice cream & frozen yogurt', 'coffee', 'pork', 'shellfish', 'other snacks', 'canned soup'}

In [17]:
usda_final = df.copy()

In [18]:
usda_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 124125 entries, 0 to 124124
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   item_name     124125 non-null  str
 1   carbs_100g    124125 non-null  float64
 2   kcal_100g     124125 non-null  float64
 3   fat_100g      124125 non-null  float64
 4   protein_100g  124125 non-null  float64
 5   source        124125 non-null  str
 6   cat_l1        124125 non-null  str
 7   cat_l2        124125 non-null  str
 8   cat_l3        124125 non-null  str
dtypes: float64(4), str(5)
memory usage: 8.5 MB

In [19]:
usda_final.cat_l1.unique()

<StringArray>
[     'condiments & sauces',                    'soups',
           'grains & pasta',              'baked goods',
                   'snacks',   'sweets & confectionery',
             'dairy & eggs',                   'fruits',
  'prepared & frozen meals',                     'meat',
               'vegetables',          'legumes & beans',
           'fish & seafood',                'beverages',
              'fats & oils', 'plant-based alternatives',
                  'poultry',              'supplements']
Length: 18, dtype: str

In [20]:
usda_final.cat_l2.unique()

<StringArray>
[         'seasoning & spices',               'prepared soup',
                       'bread',          'cookies & biscuits',
            'cakes & pastries',     'popcorn & puffed snacks',
              'jams & spreads',              'chips & crisps',
                      'cheese',   'canned & preserved fruits',
                        'rice',                    'crackers',
    'frozen dinners & entrees',                  'snack bars',
                'other snacks',              'cooking sauces',
              'prepared meals', 'processed meats & cold cuts',
                 'canned soup', 'salad dressing & mayonnaise',
           'frozen vegetables',                'canned beans',
                      'yogurt',            'fresh vegetables',
       'frozen fish & seafood',                       'sugar',
         'sausages & hot dogs',              'dairy desserts',
             'powdered drinks',           'ketchup & mustard',
               'candy & gummy',              'butter & cream',
             'pasta & noodles',                      'cereal',
   'pickles, olives & peppers',                'baking mixes',
           'canned vegetables',                   'chocolate',
    'vegetable & cooking oils',   'ice cream & frozen yogurt',
                'salsa & dips',         'chewing gum & mints',
        'canned & smoked fish',                      'salads',
                'other grains',                         'tea',
                        'eggs',           'flour & corn meal',
          'sandwiches & wraps',              'honey & syrups',
                       'pizza',                        'milk',
                      'coffee',                       'water',
            'plant-based milk',          'soda & soft drinks',
             'other beverages',           'plant-based other',
               'other poultry',         'alcoholic beverages',
         'dietary supplements',       'energy & sport drinks',
                'fresh fruits',                        'pork',
               'dried legumes',                'nuts & seeds',
                 'lamb & game',          'butter & margarine',
                  'fresh fish',                   'shellfish',
                        'beef',                     'chicken',
                'pies & tarts',                'dried fruits',
                'fruit juices']
Length: 75, dtype: str

In [21]:
usda_final.cat_l3.unique()

<StringArray>
[                   'herbs/spices/extracts',
                           'prepared soups',
                                    'bread',
                         'biscuits/cookies',
                    'sweet bakery products',
                  'savoury bakery products',
                       'cookies & biscuits',
 'popcorn, peanuts, seeds & related snacks',
                       'nut & seed butters',
                 'chips, pretzels & snacks',
 ...
          'other red and orange vegetables',
                         'fried vegetables',
               'lettuce and lettuce salads',
             'mustard and other condiments',
                   'jams, syrups, toppings',
                              'soft drinks',
                         'diet soft drinks',
                     'liquor and cocktails',
                                     'wine',
                  'sport and energy drinks']
Length: 228, dtype: str

In [22]:
usda_final[usda_final.item_name == 'beer']

,item_name,carbs_100g,kcal_100g,fat_100g,protein_100g,source,cat_l1,cat_l2,cat_l3
33970,beer,13.24,54.0,0.0,0.0,usda,beverages,soda & soft drinks,soda

In [23]:
usda_final[usda_final.cat_l3.str.contains("alcohol", case=False)]

,item_name,carbs_100g,kcal_100g,fat_100g,protein_100g,source,cat_l1,cat_l2,cat_l3
2098,colada mix pina,5.31,27.0,1.77,0.0,usda,beverages,alcoholic beverages,alcohol
2835,alcoholic non sangria sparkling,11.82,45.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol
3366,cocktail margarita mix,12.71,51.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol
3711,mix sangria,100.00,393.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol
3712,margarita mixer,1000.00,4000.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol
...,...,...,...,...,...,...,...,...,...
122027,margarita mix tequila,23.33,92.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol
122193,lime michelada mix,27.27,227.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol
122216,drink margarita mix strawberry,29.09,109.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol
122268,blossom margarita orange,22.50,83.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol
122307,drink mix sugar zero,80.00,200.0,0.00,0.0,usda,beverages,alcoholic beverages,alcohol

In [24]:
usda_final[usda_final.item_name.str.contains("bolognese", case=False)]

,item_name,carbs_100g,kcal_100g,fat_100g,protein_100g,source,cat_l1,cat_l2,cat_l3
2504,bolognese penne,11.62,123.0,5.99,4.93,usda,prepared & frozen meals,frozen dinners & entrees,frozen dinners & entrees
4316,bolognese organic sunflower,50.00,300.0,2.50,35.00,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
4729,bolognese sauce,21.33,187.0,7.33,7.00,usda,meat,processed meats & cold cuts,other deli
8604,bolognese mama marchettis sauce,6.40,88.0,5.60,4.80,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
9488,bolognese sauce,8.80,128.0,7.20,8.00,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
13457,bolognese italian meat sauce style,5.93,102.0,6.78,4.24,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
35123,bolognese foods market sauce whole,7.08,80.0,4.42,3.54,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
42918,bolognese turkey,12.94,103.0,2.65,6.76,usda,meat,processed meats & cold cuts,other deli
54450,bolognese lasagnette,78.26,848.0,34.78,52.17,usda,prepared & frozen meals,frozen dinners & entrees,pasta dinners
57712,bolognese rigatoni,20.61,170.0,6.67,6.06,usda,prepared & frozen meals,frozen dinners & entrees,frozen dinners & entrees
58939,bolognese cavatappi,17.25,129.0,3.53,6.27,usda,prepared & frozen meals,frozen dinners & entrees,frozen dinners & entrees
60972,base bolognese sauce,4.17,58.0,4.17,0.83,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
66691,bolognese lasagna,12.32,151.0,7.04,8.45,usda,prepared & frozen meals,frozen dinners & entrees,frozen dinners & entrees
74763,beef bolognese cavatappi pasta with,15.71,129.0,4.29,5.71,usda,meat,processed meats & cold cuts,other deli
83390,bolognese lentil,20.77,127.0,3.87,4.58,usda,meat,processed meats & cold cuts,other deli
85620,bolognese lentil,20.77,127.0,3.87,4.58,usda,meat,processed meats & cold cuts,other deli
87128,bolognese gourmet meat sauce,3.42,75.0,4.79,4.79,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
97094,bolognese pasta sauce,4.00,112.0,7.20,8.00,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
97275,bolognese lasagna style vegan,14.51,137.0,6.67,4.71,usda,prepared & frozen meals,frozen dinners & entrees,frozen dinners & entrees
99769,bolognese creamy pasta sauce tomato,7.08,97.0,7.96,1.77,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
100550,bolognese pasta ziti,21.33,187.0,7.33,7.00,usda,prepared & frozen meals,prepared meals,"entrees, sides & small meals"
101705,based bolognese plant sauce spicy,5.60,80.0,4.80,3.20,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
105205,barolo bolognese pasta sauce wine,8.80,128.0,7.20,8.00,usda,condiments & sauces,cooking sauces,prepared pasta & pizza sauces
111600,bolognese meatballs pasta penne with,19.70,152.0,5.05,7.07,usda,meat,processed meats & cold cuts,other deli
116394,bolognese friendly pasta sauce vegan,10.00,117.0,8.33,2.50,usda,condiments & sauces,seasoning & spices,"seasoning mixes, salts, marinades & tenderizers"
118605,based bolognese hearty plant sauce,5.60,80.0,4.80,3.20,usda,condiments & sauces,seasoning & spices,"seasoning mixes, salts, marinades & tenderizers"
118606,based bolognese plant sauce spicy,5.60,80.0,4.80,3.20,usda,condiments & sauces,seasoning & spices,"seasoning mixes, salts, marinades & tenderizers"